# Generated by Django 3.1.5 on 2021-01-27 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='countries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ADMIN', models.CharField(help_text='ISO_A3 code', max_length=100)),
                ('ISO_A3', models.CharField(help_text='ISO_A3 code', max_length=3)),
                ('ISO_A2', models.CharField(help_text='ISO_A2 code', max_length=2)),
                ('geometry', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='applicationUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IFB_member', models.BooleanField(default=False, help_text='Are you member of IFB ?')),
                ('location', models.CharField(help_text='Your laboratory', max_length=500)),
                ('position', models.CharField(help_text='Your position', max_length=500)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.countries')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
