# Generated by Django 3.1.5 on 2021-01-27 07:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sampleId', models.CharField(help_text='Biosample accession ID in original database (ENA) (e.g. SRS6007144)', max_length=255)),
                ('sampleType', models.CharField(blank=True, help_text='Anatomical origin of biosample (e.g. Bronchoalveolar lavage fluid)', max_length=255)),
                ('collectionDate', models.DateField(default=datetime.date.today, help_text='Date of biosample collection. Iso format : 2021-01-15')),
                ('country', models.CharField(help_text='Country submitter', max_length=255)),
            ],
        ),
    ]
