# Generated by Django 3.1.5 on 2021-01-27 18:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='regionsFrance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code région exemple :REG-01 ', max_length=10)),
                ('nom', models.CharField(help_text='Nom de la région : Corse', max_length=50)),
                ('features', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='vaccinFrance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, help_text='Date')),
                ('totalVaccines', models.IntegerField(default=0, help_text='Nombre de vaccins cumulés')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccins', to='France.regionsfrance')),
            ],
        ),
        migrations.CreateModel(
            name='hospitIncidReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today, help_text='Date of notice')),
                ('incid_rea', models.IntegerField(default=0, help_text='Number of new intensive care admissions in the last 24 hours')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitIncid', to='France.regionsfrance')),
            ],
        ),
    ]
